name: mi
channels:
- defaults
- conda-forge
- ooi
dependencies:
- python=2
- numpy
- scipy
- pandas
- obspy
- gevent
- matplotlib
- msgpack-python
- nose
- psycopg2
- pyzmq
- sqlalchemy
- twisted
- amqp
- librabbitmq
- ooi_port_agent
- ion-functions
- mock
- requests
- xarray
- apscheduler=2.1.0
- beautifulsoup4
- coverage
- kombu
- ntplib
- python-consul
- qpid-python
- tqdm
- vine
- pip:
  - modestimage==0.1
  - Deprecated==1.2.0
