name: mi
channels:
- defaults
- conda-forge
- ooi
dependencies:
- python=2
- pyyaml
- cython
- numpy
- scipy
- pandas
- obspy
- gevent
- matplotlib
- msgpack-python
- nose
- psycopg2
- pyzmq
- sqlalchemy
- twisted
- amqp
- librabbitmq
- mock
- requests
- xarray
- beautifulsoup4
- coverage
- kombu
- tqdm
- vine
- pip:
  - modestimage==0.1
  - apscheduler==2.1.0
  - ntplib==0.3.3
  - python-consul==0.7.0
  - qpid-python==0.32.1
  - git+https://github.com/oceanobservatories/ooi_port_agent@v0.0.42
